repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      args: ["src/", "bot.py", "server.py", "jobs.py"]
    # Run the formatter.
    - id: ruff-format
      args: ["src/", "bot.py", "server.py", "jobs.py"]