services:

  postgres:
    image: registry.tochka-tech.com/proxy_docker-io/library/postgres:14.6
    environment:
      - POSTGRES_PASSWORD=imsolnce
      - POSTGRES_USER=imsolnce
      - POSTGRES_DB=imsolnce
      - TZ=Asia/Yekaterinburg
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    command: -c fsync=off -c full_page_writes=off
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  app:
    stdin_open: true
    tty: true
    volumes:
      - ".:/opt"
    build:
      context: .
      dockerfile: Dockerfile

  server:
    volumes:
      - ".:/opt"
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: Dockerfile
    command: ["fastapi", "dev", "server.py", "--host", "0.0.0.0"]


volumes:
  pgdata:
    driver: local