version: '3'
services:

  postgres:
    image: registry.tochka-tech.com/proxy_docker-io/library/postgres:14.6
    environment:
      - POSTGRES_PASSWORD=imsolnce
      - POSTGRES_USER=imsolnce
      - POSTGRES_DB=imsolnce
      - TZ=Asia/Yekaterinburg
    ports:
      - '5432:5432'
    command: -c fsync=off -c full_page_writes=off
    tmpfs: /var/lib/postgresql/data
