"""settings

Revision ID: 1ae2304286c8
Revises: 22479a155b10
Create Date: 2025-08-09 03:06:07.760670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae2304286c8'
down_revision: Union[str, None] = '22479a155b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'currencyexchange',
        'date_at',
        existing_type=sa.DATE(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        'settings',
        'currency_update_at',
        existing_type=sa.DATE(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'settings',
        'currency_update_at',
        existing_type=sa.TIMESTAMP(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        'currencyexchange',
        'date_at',
        existing_type=sa.TIMESTAMP(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
