"""add image to anime

Revision ID: 306f4357f800
Revises: dc7d09f32aee
Create Date: 2025-05-20 00:52:34.482813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306f4357f800'
down_revision: Union[str, None] = 'dc7d09f32aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('anime', sa.Column('site_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'site_url')
    op.drop_column('anime', 'image_url')
    # ### end Alembic commands ###
