"""add uniques

Revision ID: 459d9c2ba7f2
Revises: 80dd8464d1c9
Create Date: 2025-05-19 23:57:01.102386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459d9c2ba7f2'
down_revision: Union[str, None] = '80dd8464d1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'anime', ['external_id'])
    op.create_unique_constraint('_anime_user_uc', 'subscription', ['anime_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_anime_user_uc', 'subscription', type_='unique')
    op.drop_constraint(None, 'anime', type_='unique')
    # ### end Alembic commands ###
