"""manga status

Revision ID: 582ff2c72d17
Revises: ad41ab9c49cc
Create Date: 2025-06-07 01:38:30.307172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582ff2c72d17'
down_revision: Union[str, None] = 'ad41ab9c49cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga', 'status')
    # ### end Alembic commands ###
