"""uniqueexchange

Revision ID: 88b0daad505b
Revises: 1ae2304286c8
Create Date: 2025-08-09 03:19:50.872650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b0daad505b'
down_revision: Union[str, None] = '1ae2304286c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('currency_date_idx', table_name='currencyexchange')
    op.create_index(
        'currency_date_idx', 'currencyexchange', ['currency', 'date_at'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('currency_date_idx', table_name='currencyexchange')
    op.create_index(
        'currency_date_idx', 'currencyexchange', ['currency', 'date_at'], unique=False
    )
    # ### end Alembic commands ###
