"""currencyexchange

Revision ID: bea2d1882b0f
Revises: a3605d6fe5cb
Create Date: 2025-08-09 02:15:03.043810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bea2d1882b0f'
down_revision: Union[str, None] = 'a3605d6fe5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'currencyexchange',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('date_at', sa.Date(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'currency_date_idx', 'currencyexchange', ['currency', 'date_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('currency_date_idx', table_name='currencyexchange')
    op.drop_table('currencyexchange')
    # ### end Alembic commands ###
