"""add anime table

Revision ID: d2ba90f0f644
Revises: 609e0c70d503
Create Date: 2025-05-19 20:18:00.365157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ba90f0f644'
down_revision: Union[str, None] = '609e0c70d503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('next_air_at', sa.DateTime(), nullable=False),
    sa.Column('episodes_number', sa.Integer(), nullable=False),
    sa.Column('episodes_aired', sa.Integer(), nullable=False),
    sa.Column('last_notification_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscription', sa.Column('anime_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subscription', 'anime', ['anime_id'], ['id'])
    op.drop_column('subscription', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'anime_id')
    op.drop_table('anime')
    # ### end Alembic commands ###
