# This is a basic workflow to help you get started with Actions

name: Deploy ssh

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - name: Run ruff check
        run: ruff check ./src ./bot.py ./server.py
      - name: Run ruff format
        run: ruff format --check --diff ./src ./bot.py ./server.py

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: ruff

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/telegram_bot
          git pull origin main
          git status
          source .venv/bin/activate
          alembic upgrade head
          uv sync
          cd front
          npm run build
          systemctl restart telegram_bot
          systemctl restart telegram_bot_jobs
          systemctl restart web_server